"""
Ingest movie knowledge documents into Milvus for hybrid RAG retrieval.

Creates a collection with:
  - dense_vector  (FLOAT_VECTOR, dim=1536) — OpenAI text-embedding-3-small
  - sparse_vector (SPARSE_FLOAT_VECTOR)    — BM25, auto-generated by Milvus
  - text          (VARCHAR)                — source text for BM25 tokenisation
  - source        (VARCHAR)                — file path metadata

If the collection already exists with the old schema (dense-only), it is
dropped and recreated automatically. Use --reset to force a clean rebuild
on an existing hybrid-schema collection.

Usage:
  python scripts/ingest.py                    # ingest ./docs/
  python scripts/ingest.py path/to/docs/      # ingest a specific directory
  python scripts/ingest.py path/to/file.md    # ingest a single file
  python scripts/ingest.py docs/ --reset      # drop collection, then ingest
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from pymilvus import (
    DataType,
    Function,
    FunctionType,
    MilvusClient,
)

from src.config import get_config

# TextLoader handles both plain text and markdown — no heavy unstructured dep needed
LOADER_MAP = {
    ".txt": TextLoader,
    ".md":  TextLoader,
}

DEFAULT_CHUNK_SIZE    = 800
DEFAULT_CHUNK_OVERLAP = 100
BATCH_SIZE            = 50
TEXT_MAX_LEN          = 8192   # Milvus VARCHAR limit per field; chunks are ~800 chars


# ── Document loading ──────────────────────────────────────────────────────────

def load_files(path: Path) -> list[Document]:
    paths = [path] if path.is_file() else list(path.rglob("*"))
    docs: list[Document] = []
    for p in sorted(paths):
        if not p.is_file() or p.suffix.lower() not in LOADER_MAP:
            continue
        loader = LOADER_MAP[p.suffix.lower()](str(p))
        loaded = loader.load()
        for doc in loaded:
            doc.metadata.setdefault("source", str(p))
        docs.extend(loaded)
        print(f"  Loaded: {p} ({len(loaded)} doc(s))")
    return docs


def chunk_docs(docs: list[Document]) -> list[Document]:
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=DEFAULT_CHUNK_SIZE,
        chunk_overlap=DEFAULT_CHUNK_OVERLAP,
        separators=["\n\n", "\n", ". ", " ", ""],
    )
    return splitter.split_documents(docs)


# ── Collection management ─────────────────────────────────────────────────────

def _build_schema(cfg) -> tuple:
    """Return (schema, index_params) for a hybrid collection."""
    schema = MilvusClient.create_schema(auto_id=True, enable_dynamic_field=False)
    schema.add_field("id",            DataType.INT64,          is_primary=True)
    schema.add_field("text",          DataType.VARCHAR,        max_length=TEXT_MAX_LEN, enable_analyzer=True)
    schema.add_field("sparse_vector", DataType.SPARSE_FLOAT_VECTOR)
    schema.add_field("dense_vector",  DataType.FLOAT_VECTOR,   dim=cfg.embedding_dim)
    schema.add_field("source",        DataType.VARCHAR,        max_length=512)

    schema.add_function(Function(
        name="bm25",
        input_field_names=["text"],
        output_field_names=["sparse_vector"],
        function_type=FunctionType.BM25,
    ))

    client = MilvusClient(uri=cfg.milvus_uri)
    index_params = client.prepare_index_params()
    index_params.add_index(
        field_name="dense_vector",
        index_name="dense_idx",
        index_type="IVF_FLAT",
        metric_type="IP",
        params={"nlist": 128},
    )
    index_params.add_index(
        field_name="sparse_vector",
        index_name="sparse_idx",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
        params={"bm25_k1": 1.2, "bm25_b": 0.75},
    )
    return schema, index_params


def _has_sparse_field(client: MilvusClient, collection_name: str) -> bool:
    try:
        info = client.describe_collection(collection_name)
        return any(f["name"] == "sparse_vector" for f in info.get("fields", []))
    except Exception:
        return False


def ensure_collection(client: MilvusClient, cfg, reset: bool) -> None:
    """Create or migrate the Milvus collection for hybrid search."""
    exists = client.has_collection(cfg.milvus_collection)

    if exists:
        if reset:
            print(f"  --reset: dropping '{cfg.milvus_collection}'")
            client.drop_collection(cfg.milvus_collection)
        elif not _has_sparse_field(client, cfg.milvus_collection):
            print(
                f"  Old dense-only schema detected — dropping '{cfg.milvus_collection}' "
                f"to apply hybrid schema (BM25 + dense)."
            )
            client.drop_collection(cfg.milvus_collection)
        else:
            print(f"  Collection '{cfg.milvus_collection}' has hybrid schema — appending.")
            return

    print(f"  Creating hybrid collection '{cfg.milvus_collection}'...")
    schema, index_params = _build_schema(cfg)
    client.create_collection(
        collection_name=cfg.milvus_collection,
        schema=schema,
        index_params=index_params,
    )
    print(f"  Collection ready (dense_vector dim={cfg.embedding_dim}, BM25 sparse).")


# ── Embedding + insert ────────────────────────────────────────────────────────

def embed_and_insert(client: MilvusClient, cfg, chunks: list[Document]) -> int:
    """Embed chunks with OpenAI, insert text + dense_vector + source into Milvus."""
    embedder = OpenAIEmbeddings(
        model="text-embedding-3-small",
        openai_api_key=cfg.openai_api_key,
    )

    texts   = [c.page_content[:TEXT_MAX_LEN] for c in chunks]
    sources = [c.metadata.get("source", "unknown") for c in chunks]

    print(f"\n  Embedding {len(texts)} chunks via OpenAI text-embedding-3-small...")
    dense_vecs = embedder.embed_documents(texts)

    rows = [
        {"text": text, "dense_vector": vec, "source": source}
        for text, vec, source in zip(texts, dense_vecs, sources)
    ]

    inserted = 0
    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i : i + BATCH_SIZE]
        client.insert(cfg.milvus_collection, batch)
        inserted += len(batch)
        print(f"  Inserted {inserted}/{len(rows)} chunks", end="\r")

    print(f"  Inserted {inserted}/{len(rows)} chunks")
    return inserted


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    args    = [a for a in sys.argv[1:] if not a.startswith("--")]
    reset   = "--reset" in sys.argv
    target  = Path(args[0]) if args else Path("docs")

    if not target.exists():
        print(f"ERROR: Path not found: {target}")
        sys.exit(1)

    cfg = get_config()
    print(f"\nCineAI Hybrid Ingest")
    print(f"  Source    : {target.resolve()}")
    print(f"  Milvus    : {cfg.milvus_uri}")
    print(f"  Collection: {cfg.milvus_collection}")
    print(f"  Schema    : dense ({cfg.embedding_dim}d) + BM25 sparse")
    if reset:
        print(f"  Mode      : reset (drop + recreate)")
    print()

    client = MilvusClient(uri=cfg.milvus_uri)

    print("Preparing collection...")
    ensure_collection(client, cfg, reset)

    print("\nLoading documents...")
    docs = load_files(target)
    if not docs:
        print("No supported files found (.txt, .md)")
        sys.exit(1)

    print(f"\nChunking {len(docs)} document(s)...")
    chunks = chunk_docs(docs)
    print(f"  → {len(chunks)} chunks (size={DEFAULT_CHUNK_SIZE}, overlap={DEFAULT_CHUNK_OVERLAP})")

    count = embed_and_insert(client, cfg, chunks)

    print(f"\n✓ Hybrid ingest complete: {count} chunks in '{cfg.milvus_collection}'")
    print(f"  Queries now use BM25 sparse + dense embeddings (RRF fusion).")
    print(f"  Exact title matches like 'The Dark Knight' will now rank correctly.\n")


if __name__ == "__main__":
    main()
